/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-25 04:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import control.UserControl;
import java.util.Locale;
import vteam.frame.system.message.MessageResourceImpl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Expires", "Tues,01 Jan 1980 00:00:00 GMT");
	//获取当前locale

	//判断是否已登陆
	UserControl uc = new UserControl(session);
	Locale locale = uc.getLocale();
	//获取多语言
	MessageResourceImpl message = MessageResourceImpl.getInstance();
	message.setLanLocal(locale);

      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>");
      out.print(message.getMessage("LBL_TYBLYWXT") );
      out.write("</title>\r\n");
      out.write("<script language=\"JavaScript\" src=\"../jscript/submit.js\"></script>\r\n");
      out.write("<script language=\"javaScript\">\r\n");
      out.write("function removeline(){\r\n");
      out.write("\r\n");
      out.write("if(event.clientX<0&&event.clientY<0){\r\n");
      out.write(" //document.write('<iframe width=\"100\" height=\"100\" src=\"login.jsp\"></iframe><OBJECT classid=CLSID:8856F961-340A-11D0-A96B-00C04FD705A2 height=0  id=WebBrowser width=0></OBJECT>');\r\n");
      out.write("\t//document.all.WebBrowser.ExecWB(45,1);\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<frameset rows=\"77,*\" cols=\"*\" frameborder=\"0\" framespacing=\"0\" id=\"all\"  onUnload=\"removeline();\">\r\n");
      out.write("\t<frame src=\"../include/title.jsp\" name=\"top\" scrolling=\"no\">\r\n");
      out.write("\t<frameset id=\"indexFrame\" rows=\"*\" cols=\"0,6,*\" frameborder=\"0\" framespacing=\"0\">\r\n");
      out.write("\t\t<frame name=\"menu\" noresize src=\"../menu/menu.jsp\">\r\n");
      out.write("\t\t<frame name=\"mid\" noresize=\"noresize\" src=\"middle.jsp\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("\t\t<frame name=\"view\" id=\"view\" noresize src=\"main.jsp\" scrolling=\"yes\">\r\n");
      out.write("\t</frameset>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</frameset>\r\n");
      out.write("<noframes><body onkeydown=\"javascript:closeIEkey();\" oncontextmenu=\"javascript:closeRightKey();\">\r\n");
      out.write("</body></noframes>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
