/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-25 04:40:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Enumeration;
import java.util.StringTokenizer;
import vteam.frame.system.sysconst.FrameConst;
import vteam.frame.system.message.MessageResourceImpl;
import control.UserControl;
import vteam.csps.common.BussConst;
import vteam.common.tools.util.ChkMethod;
import com.crystaldecisions.report.web.viewer.CrystalReportInteractiveViewer;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

        MessageResourceImpl message = MessageResourceImpl.getInstance();
        String language = request.getParameter("LanguageType");
        int pwdint = 20;

    	String loginflag = "";
    	String userid = "";
    	String password = "";

        //请输入帐号!   MSG_IN_A
	//请输入密码!   MSG_IN_P
	//密码长度不能小于6位!     MSG_PWD_NUM
	//确定提交!     MSG_SUBMIT
      try {
        UserControl uc = new UserControl(session);
        java.util.Locale locale = uc.getLocale();

        if(locale == null) {
            if(language == null){
            	language = BussConst.DEFAULT_LANGUAGE;
            }
            String[] tl = language.split("_");
            locale = new java.util.Locale(tl[0],tl[1]);
        }else{
            language = locale.toString();
        }

        message.setLanLocal(locale);
        
		//[1.1]
		loginflag = (String) request.getAttribute("FLAG");
		
	if (uc.getUserID() != null && ChkMethod.isBlank(loginflag)) {//[1.1]
        session.removeAttribute(FrameConst.MESSAGE_KEY); //release resource
        session.removeAttribute(BussConst.VCHMAP_KEY);
        uc.logOut();
        session.removeAttribute(uc.getUserID());
        //uc.logOut(); peroo:将logOut()移到上面！解决了用户登出不能完全清空session的问题
        //add For report temp files delete start
        Enumeration e = session.getAttributeNames();
        while(e.hasMoreElements()){
          Object obj = e.nextElement();
          //System.out.println("begin logout viewer obj=" + obj);
          if((String.valueOf(obj)).endsWith("viewer")){
            CrystalReportInteractiveViewer viewer = null;
            Object value = session.getAttribute(String.valueOf(obj));
            viewer =(CrystalReportInteractiveViewer) value;
            viewer.dispose();
          }
          
        }

      }

        //20071011 javarain add
    String Agent = request.getHeader("User-Agent");
	StringTokenizer st = new StringTokenizer(Agent,";");
	st.nextToken();
	//得到用户的浏览器名
	String userbrowser = st.nextToken();
	//System.out.println("userbrowser="+userbrowser);
	//得到用户的操作系统名
	String useros = st.nextToken();
        //System.out.println("client user os="+useros);
        if(useros!=null){
          //System.out.println("os ="+useros.trim().substring(11,14));
            if(useros.trim().substring(11,14).compareTo("5.0")<1){//os 2000
              pwdint = 18;//控件的size大小
            }
        }
        
		//[1.1] begin


		userid = (String) request.getAttribute("USERID");
		if (userid == null) {
			userid = "";
		}
		password = (String) request.getAttribute("PASSWORD");
		if (password == null) {
			password = "";
		}
		//[1.1] end 
		
    }catch (Exception e) {
      System.out.println("login.jsp user logout hase Exception:"+e);
    }

    String path = request.getContextPath();
   // System.out.println("path:"+path);
    String copyright = message.getMessage("LBL_COPYRIGHT"); // "版权所有 &copy; 2001-2007 天逸系统（武汉）有限公司";
    //String pic01 = "../images/" + language + "/grdl_pic01_10.gif";
    //String pic02 = "../images/" + language + "/grdl_pic01_11.gif";
    String pic03 =  path + "/images/" + language + "/grdl_on01.gif";
    String pic04 =  path + "/images/" + language + "/grdl_on03.gif";
   String desc_username = message.getMessage("FLD_USER");
   String desc_password = message.getMessage("FLD_PASSWORD");

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>User Login</title>\r\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/css/vteam.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("background: #EDEDED url(");
      out.print(path);
      out.write("/images/");
      out.print(language);
      out.write("/mian_1.jpg)  0px -82px ;\r\n");
      out.write("font-size:12px;\r\n");
      out.write("}\r\n");
      out.write(".text{\r\n");
      out.write("width:120px;\r\n");
      out.write("height:20px;\r\n");
      out.write("border:1px solid #376F9B;}\r\n");
      out.write(".copyright{color: #FFF;\r\n");
      out.write("font-size: 14px;}\r\n");
      out.write(".style1 {font-size: 12px;\r\n");
      out.write("color: #000;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\t\t<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("function reurl(){\r\n");
      out.write("  url = location.href; //把当前页面的地址赋给变量 url\r\n");
      out.write("  var times = url.split(\"?\"); //分切变量 url 分隔符号为 \"?\"\r\n");
      out.write("  if(times[times.length - 1] != 1){ //如果?后的值不等于1表示没有刷新\r\n");
      out.write("\turl += \"?1\"; //把变量 url 的值加入 ?1\r\n");
      out.write("        document.form1.action = url;\r\n");
      out.write("    \tdocument.form1.submit();\r\n");
      out.write("\t//self.location.replace(url); //刷新页面\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setFocus(){\r\n");
      out.write("   reurl();\r\n");
      out.write("   document.form1.userid.focus();\r\n");
      out.write("}\r\n");
      out.write("//function toLogin(){\r\n");
      out.write("  // document.form1.action=\"../dobusiness.do?ACTIONID=LOGIN\";\r\n");
      out.write("  // document.form1.submit();\r\n");
      out.write("  // return;\r\n");
      out.write("//}\r\n");
      out.write("\r\n");
      out.write("//jeff mod  081119\r\n");
      out.write("//[1.1]\r\n");
      out.write("function toLogin2(){\r\n");
      out.write("  \tvar urlsel = \"");
      out.print(path);
      out.write("/main/moduleselect.jsp\";\r\n");
      out.write("  \t//模态页面最小宽度只能100px\r\n");
      out.write("    var selwinfeatures = \"dialogHeight=330px,dialogWidth=100px,dialogTop=235px,dialogLeft=240px,resizable=no,status=no,scrollbars=no,titlebar=no,toolbar=no,menubar=no,location=no\";\r\n");
      out.write(" \tvar module = window.showModalDialog(urlsel,\"\",selwinfeatures);\r\n");
      out.write("    if (module!=\"cancel\"){//模态窗口点取消不继续执行登陆后台\r\n");
      out.write("\tdocument.form1.all(\"module\").value=module.toString();\r\n");
      out.write("\turl=\"");
      out.print(path);
      out.write("/dobusiness.do?ACTIONID=LOGIN\";\r\n");
      out.write("    document.form1.action=url;\r\n");
      out.write("    document.form1.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function login(){\r\n");
      out.write(" if(");
      out.print(loginflag);
      out.write("){\r\n");
      out.write("    toLogin2();\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("function toLogin(){\r\n");
      out.write("     document.form1.action=\"../dobusiness.do?ACTIONID=LOGIN\";\r\n");
      out.write("     document.form1.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//[1.1] end \r\n");
      out.write("\r\n");
      out.write("function fnTrapKD(){\r\n");
      out.write("    if (event.keyCode == 13) {\r\n");
      out.write("        FieldCheck();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function FieldCheck(){\r\n");
      out.write("    var s = true;\r\n");
      out.write("    if(document.form1.userid.value==null||document.form1.userid.value==''){\r\n");
      out.write("        s = false;\r\n");
      out.write("        alert(\"");
      out.print(message.getMessage("MSG_IN_A"));
      out.write("\");\r\n");
      out.write("        document.form1.userid.focus();\r\n");
      out.write("        return s;\r\n");
      out.write("    }\r\n");
      out.write("    if(document.form1.password.value==null||document.form1.password.value==''){\r\n");
      out.write("        s = false;\r\n");
      out.write("        alert(\"");
      out.print(message.getMessage("MSG_IN_P"));
      out.write("\");\r\n");
      out.write("        document.form1.password.focus();\r\n");
      out.write("        return s;\r\n");
      out.write("    }\r\n");
      out.write("    if(s){\r\n");
      out.write("        if((document.form1.password.value.length<6)){\r\n");
      out.write("            s = false;\r\n");
      out.write("            alert(\"");
      out.print(message.getMessage("MSG_PWD_NUM"));
      out.write("\");\r\n");
      out.write("            document.form1.password.focus();\r\n");
      out.write("            return s;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    toLogin();\r\n");
      out.write("    return s;\r\n");
      out.write("}\r\n");
      out.write("function IsInteger(string){\r\n");
      out.write("    var integer;\r\n");
      out.write("    integer = parseInt(string,10);\r\n");
      out.write("    if (isNaN(integer)){\r\n");
      out.write("            return false;\r\n");
      out.write("    }else{\r\n");
      out.write("        var num =integer.toString();\r\n");
      out.write("        if (num.length!=string.length){\r\n");
      out.write("            var length =parseInt(string.length-num.length);\r\n");
      out.write("            for (var j=0;j<length;j=j+1){\r\n");
      out.write("                num='0'+num;\r\n");
      out.write("            }\r\n");
      out.write("            if (num!=string) {\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("}\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("function chgLan(t){\r\n");
      out.write("    document.getElementById(\"LanguageType\").value = t;\r\n");
      out.write("    document.form1.action = \"login.jsp?1\";\r\n");
      out.write("    document.form1.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onLoad=\"setFocus();login()\">\r\n");
      out.write("<form name=\"form1\"  method=\"post\" action=\"../dobusiness.do?ACTIONID=LOGIN\" onsubmit=\"return(FieldCheck())\">\r\n");
      out.write("<input type=\"hidden\" name=\"LanguageType\" id=\"LanguageType\" value=\"");
      out.print(language);
      out.write("\"/>\r\n");
      out.write("\t\t\t<!--jeff mod 081119 begin-->\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"module\" name=\"module\" value=\"\" />\r\n");
      out.write("\t\t\t<!--[1.1]-->\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"loginflag\" name=\"loginflag\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(loginflag);
      out.write("\" />\r\n");
      out.write("\t\t\t<!--jeff mod 081119 end-->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("  <table width=\"660\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"71\" colspan=\"3\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"77\" colspan=\"3\" valign=\"top\"><img src=\"");
      out.print(path);
      out.write("/images/");
      out.print(language);
      out.write("/mian1_3.jpg\" width=\"660\" height=\"77\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td width=\"344\" height=\"240\" valign=\"top\"><img src=\"");
      out.print(path);
      out.write("/images/");
      out.print(language);
      out.write("/mian1_5.jpg\" width=\"344\" height=\"240\" /></td>\r\n");
      out.write("      <td colspan=\"2\" valign=\"top\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"");
      out.print(path);
      out.write("/images/");
      out.print(language);
      out.write("/mian1_6.jpg\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"7\" height=\"61\">&nbsp;</td>\r\n");
      out.write("            <td width=\"55\">&nbsp;</td>\r\n");
      out.write("            <td width=\"82\">&nbsp;</td>\r\n");
      out.write("            <td width=\"72\">&nbsp;</td>\r\n");
      out.write("            <td width=\"100\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\t\t     <tr>\r\n");
      out.write("            <td height=\"35\">&nbsp;</td>\r\n");
      out.write("            <td colspan=\"3\" valign=\"top\"><span class=\"style1\">");
      out.print(desc_username);
      out.write("</span>\r\n");
      out.write("           <INPUT id=\"userid\" maxLength=\"18\" name=\"userid\" tabindex=\"1\" class=\"text\" value=\"");
      out.print(userid);
      out.write("\">\r\n");
      out.write("            </td>\r\n");
      out.write("          <td valign=\"top\"><a href=\"javascript:chgLan('en_US');\"><img src=\"");
      out.print(path);
      out.write("/images/language1.gif\" border=\"0\"></a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"35\">&nbsp;</td>\r\n");
      out.write("            <td colspan=\"3\" valign=\"top\"><span class=\"style1\">");
      out.print(desc_password);
      out.write("</span>\r\n");
      out.write("            <INPUT id=\"password\" type=\"password\" name=\"password\" onkeydown=\"javascript:fnTrapKD();\" tabindex=\"2\" class=\"text\" value=\"");
      out.print(password);
      out.write("\"></td>\r\n");
      out.write("          <td valign=\"top\"><a href=\"javascript:chgLan('zh_TW');\"><img src=\"");
      out.print(path);
      out.write("/images/language2.gif\" border=\"0\"></a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"35\" >&nbsp;</td>\r\n");
      out.write("            <td align=\"left\" valign=\"top\"><IMG src=\"");
      out.print(pic03);
      out.write("\" style='cursor:hand' name=\"submit1\"  border=\"0\" id=\"submit1\" onclick=\"javascript:FieldCheck();\"></td>\r\n");
      out.write("            <td align=\"center\" valign=\"top\"><IMG  style='cursor:hand' src=\"");
      out.print(pic04);
      out.write("\"  border=\"0\" onclick=\"document.form1.reset();\"></td>\r\n");
      out.write("            <td align=\"left\" valign=\"top\"></td>\r\n");
      out.write("          <td valign=\"top\" ><a href=\"javascript:chgLan('zh_CN');\"><img src=\"");
      out.print(path);
      out.write("/images/language3.gif\" border=\"0\"></a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"40\">&nbsp;</td>\r\n");
      out.write("            <td>&nbsp;</td>\r\n");
      out.write("            <td align=\"center\" valign=\"top\"></td>\r\n");
      out.write("            <td valign=\"top\"></td>\r\n");
      out.write("          <td valign=\"top\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"28\">&nbsp;</td>\r\n");
      out.write("            <td colspan=\"3\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("          <td>&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"6\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("      </table></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"91\" colspan=\"3\" valign=\"top\"><img src=\"");
      out.print(path);
      out.write("/images/");
      out.print(language);
      out.write("/mian1_7.jpg\" width=\"660\" height=\"71\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"21\" colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("    <td width=\"58\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"50\" colspan=\"2\" valign=\"top\"></td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td height=\"10\" colspan=\"2\" valign=\"top\"></td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("      <td height=\"40\" colspan=\"2\" valign=\"top\" class=\"copyright\" align=\"middle\">  ");
      out.print(copyright);
      out.write("</td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"1\"></td>\r\n");
      out.write("      <td width=\"258\"></td>\r\n");
      out.write("      <td></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write("              </FORM>\r\n");
      out.write("  </BODY>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
