/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-25 04:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import java.util.Iterator;
import control.UserControl;
import vteam.frame.system.sysconst.FrameConst;
import java.util.ArrayList;
import vteam.frame.system.exception.*;
import vteam.csps.common.MessageConst;
import vteam.csps.common.BussConst;
import vteam.web.query.BussOperQuery;
import vteam.web.query.BOPQuery;
import vteam.web.menu.Menu;
import vteam.frame.system.message.MessageResourceImpl;
import java.util.Locale;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	response.setHeader("Expires", "Tues,01 Jan 1980 00:00:00 GMT");
	//获取当前locale

	//判断是否已登陆
	UserControl uc = new UserControl(session);
	Locale locale = uc.getLocale();
	//WebUserControl webuc = new WebUserControl();
	//webuc.UserControl(session);
	if (uc.getUserID() == null) {
		//System.out.println("userid is null.");
		StException se = new StException(MessageConst.MSG_USER_NOTLOGIN);
		ArrayList list = new ArrayList();
		list.add(se);
		ExceptionDisplayor ex = new ExceptionDisplayor(locale, list);
		list = ex.getDisplayList();
		session.setAttribute(FrameConst.MESSAGE_KEY, list);
		list = null;
		se = null;
		ex = null;
		response.sendRedirect(BussConst.PATH_LOGOUT_MSG);
		return;
	}

	//获取多语言
	MessageResourceImpl message = MessageResourceImpl.getInstance();
	message.setLanLocal(locale);

	Menu menu = new Menu();
	menu.setMenuLocale(locale);
	String VteamSystemNote = menu.getNoticeOfIndex();
	String beltlignt_desc = menu.getBELTDESCOfIndex();
	String SystemBulletinDesc = message.getMessage("FLD_SYS_BOARD");
	String AppDataDesc = message.getMessage("BTN_NEEDAPPDATA");
	String AppDataQueryDesc = message.getMessage("BTN_NEEDAPPDATAQ");

	String WAppDataDesc = message.getMessage("BTN_BAPPDATA");
	String WAppDataQueryDesc = message.getMessage("BTN_BAPPDATAQUERY");
	//jeff 080909 add 
	String WRefuseDataDesc = message.getMessage("BTN_REFUSEDATA");
	String WRefuseDataQueryDesc = message.getMessage("BTN_REFUSEDATAQUERY");

	//zhaochen 081023 add
	String parmRefuseDataQuery = message.getMessage("BTN_PARMREFUSEDATAQUERY"); //参数拒绝资料查询
	String txRefuseDataQuery = message.getMessage("BTN_TXREFUSEDATAQUERY"); //交易拒绝资料查询            

	String InvoiceInfo = message.getMessage("SEP_INVINFO");
	//String BopErrNo=message.getMessage("BTN_BOPERRNO");
	//String BopMzNo=message.getMessage("BTN_BOPMZNO");
	String InvQuery = message.getMessage("BTN_INVQUERY");
	String BopInfo = message.getMessage("SEP_BOPINFO");
	String BopQuery = message.getMessage("BTN_BOPQUERY");
	String HintInfo = message.getMessage("SEP_HINT");
	String InvHint = message.getMessage("SEP_RECEIVEHINT");
	String LoanHint = message.getMessage("SEP_LOANHINT");
	String LoanErrHint = message.getMessage("SEP_LOANERRHINT");
	String ExpHint = message.getMessage("SEP_EXPHINT");
	//增加额度到期提示信息  add by toby 2008.06.06
	String EXPIRYDATE = message.getMessage("SEP_EXPIRYDATE");
	String WatHint = message.getMessage("SEP_WATHINT");
	String cmfcreditremind = message.getMessage("TIT_CMFCREDITREMIND"); //[1.4]
	String powfloanremind = message.getMessage("TIT_POWFLOANREMIND"); //[1.4] 
	String edibcedi = message.getMessage("SEP_EDIBCEDI");//Jarvis 增加EDI待补充信息提示 
	String ediefbcedi = message.getMessage("SEP_EDIEFBCEDI");
	String ediifbcedi = message.getMessage("SEP_EDIIFBCEDI");
	String cmfreaclbquery = message.getMessage("TIT_CMFREASTORAGEAMTQUERY");//[1.8]
	//20070412 add by Karen收支申报错误信息数
	//获取可操作分行
	//BussOper  bussOper= new BussOper();
	//        BussOperQuery bussOper = new BussOperQuery();
	//        HashMap bchmap = new HashMap();
	//        bchmap = bussOper.getBussOperBch(uc.getUserID());
	//	StringBuffer mapBuff = new StringBuffer();
	//      	if(bchmap != null && bchmap.size() > 0){
	//        	int icount = 0;
	//                Iterator it = bchmap.keySet().iterator();
	//                while(it.hasNext()){
	//                	if(icount > 0) mapBuff.append(",");
	//                        mapBuff.append("'").append((String)it.next()).append("'");
	//                        icount++;
	//                        }
	//          }
	//          //20070412 add by Karen收支申报错误信息数
	//          BOPQuery bq = new BOPQuery();
	//          int errno = bq.getBOPErrMsgCount(mapBuff.toString());
	//          //20070412 add by Karen收支申报魔掌信息数
	//          int mzno = bq.getBOPMZCount(mapBuff.toString());

	//zhaochen mod 0801023
	//民生新需求    
	// [1.1] 改变了函数的参数表
	HashMap map = menu.getRefuseInfoOfIndex(uc);
	//jeff mod 0916
	String count = (String) map.get("count");
	StringBuffer sb = new StringBuffer();
	sb = sb.append("(").append(count).append(")");
	// [1.1] 改变了函数的参数表
	HashMap map1 = menu.getParmRefuseInfoOfIndex(uc);
	String count1 = (String) map1.get("count");
	StringBuffer sb1 = new StringBuffer();
	sb1 = sb1.append("(").append(count1).append(")");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("\t\t<title>main</title>\r\n");
      out.write("\t\t<link href=\"../css/vteam.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"../jscript/submit.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"../jscript/menuTree.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<BODY leftMargin=\"0\" topMargin=\"0\" rightMargin=\"0\">\r\n");
      out.write("\t\t<form name=\"form1\" id=\"form1\" method=\"post\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<TABLE class=\"normal\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"3%\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"46%\" valign=\"top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TABLE class=\"mainBox\" cellpadding=\"2\" cellspacing=\"1\" width=\"80%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR  align=\"center\" height=\"40\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(message.getMessage("LBL_MYWORK") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD bgcolor=\"#F3F3F3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(AppDataDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/appinfo.jsp\"><u>");
      out.print(AppDataQueryDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD bgcolor=\"#F3F3F3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(WAppDataDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/checkappinfo.jsp\"><u>");
      out.print(WAppDataQueryDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD bgcolor=\"#F3F3F3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(WRefuseDataDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/parmqueryrefuseinfo.jsp\"><u>");
      out.print(parmRefuseDataQuery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(sb1.toString());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/queryrefuseinfo.jsp\"><u>");
      out.print(txRefuseDataQuery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(sb.toString());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<!-- 1.7  start-->\r\n");
      out.write("\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD bgcolor=\"#F3F3F3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(edibcedi);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t");

					if (("EF").equals(uc.getBussinessModule())|| ("").equals(uc.getBussinessModule())) {
					
					if(uc.hasFun("EDIEFBC")){	
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/edibcedi.jsp?EDIFLAG=EF\"><u>");
      out.print(ediefbcedi);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
								}
							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");

					if (("IF").equals(uc.getBussinessModule())|| ("").equals(uc.getBussinessModule())) {
					
						if(uc.hasFun("EDIIFBC")){	
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/edibcedi.jsp?EDIFLAG=IF\"><u>");
      out.print(ediifbcedi);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
								}
							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<!-- 1.7  end -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50%\" valign=\"top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TABLE class=\"mainBox\" cellpadding=\"2\" cellspacing=\"1\" width=\"80%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\"  align=\"center\" height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(HintInfo);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if (("EF").equals(uc.getBussinessModule()) || ("").equals(uc.getBussinessModule())) {
										
									  if(uc.hasFun("EFYSZK10DAY")||uc.hasFun("EFYSZKJT")||uc.hasFun("EFYSZKDQ10DAY")||
									  uc.hasFun("EFYSZKDQ30DAY")||uc.hasFun("EFYSZKDQ60DAY")||
									  uc.hasFun("EFYSZKDQ90DAY")||uc.hasFun("EFYSZKALL")||uc.hasFun("EFYSZKSJ5DAY")||
									  uc.hasFun("EFDBFK10DAY")||uc.hasFun("EFDBFK5DAY")||uc.hasFun("EFDBFKYXY")||
									  uc.hasFun("EFBXGSPK")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/efinvhint.jsp\"><u>");
      out.print(InvHint);
      out.write("[EF]</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									 }
									}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if (("IF").equals(uc.getBussinessModule()) || ("").equals(uc.getBussinessModule())) {
									 if(uc.hasFun("IFYSZK10DAY")||uc.hasFun("IFYSZKJT")||
									 uc.hasFun("IFYSZKDQ10DAY")||uc.hasFun("IFYSZKDQ30DAY")||
									 uc.hasFun("IFYSZKDQ60DAY")||uc.hasFun("IFYSZKDQ90DAY")||
									 uc.hasFun("IFYSZKALL")||uc.hasFun("IFYSZKSJ5DAY")||
									 uc.hasFun("IFDBFK10DAY")||uc.hasFun("IFDBFK5DAY")||
									 uc.hasFun("IFDBFKYXY")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/ifinvhint.jsp\"><u>");
      out.print(InvHint);
      out.write("[IF]</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									  }
									}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if (("SC").equals(uc.getBussinessModule()) || ("").equals(uc.getBussinessModule())) {
									 if(uc.hasFun("SCJTDQPD")||uc.hasFun("SCDQPD")||uc.hasFun("SCSJ5DAY")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/scwathint.jsp\"><u>");
      out.print(WatHint);
      out.write("[SC]</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										 }
										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.5] [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												//if (("EF").equals(uc.getBussinessModule()) || ("SC").equals(uc.getBussinessModule())
												//|| ("AR").equals(uc.getBussinessModule())|| ("CMF").equals(uc.getBussinessModule())
												//|| ("POWF").equals(uc.getBussinessModule())|| ("").equals(uc.getBussinessModule())) {
											if(uc.hasFun("LOANDQEF")){	
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}else if(uc.hasFun("LOANDQSC")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}else if(uc.hasFun("LOANDQAR")){ 
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}else if(uc.hasFun("LOANDQCMF")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}else if(uc.hasFun("LOANDQPOWF")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t        ");
}else if(("").equals(uc.getBussinessModule())&&(uc.hasFun("LOANDQEF")||uc.hasFun("LOANDQSC")||uc.hasFun("LOANDQAR")||uc.hasFun("LOANDQCMF")||uc.hasFun("LOANDQPOWF"))){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanhint.jsp\"><u>");
      out.print(LoanHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3] [1.6] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												//if (("EF").equals(uc.getBussinessModule()) || ("SC").equals(uc.getBussinessModule())
												//|| ("AR").equals(uc.getBussinessModule())
												//|| ("").equals(uc.getBussinessModule())) {
										if(uc.hasFun("LOANSWYBEF")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanerrhint.jsp\"><u>");
      out.print(LoanErrHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if(uc.hasFun("LOANSWYBSC")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanerrhint.jsp\"><u>");
      out.print(LoanErrHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
 
                                    }else if(uc.hasFun("LOANSWYBAR")){
                                    
      out.write("\r\n");
      out.write("                                    <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanerrhint.jsp\"><u>");
      out.print(LoanErrHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
 
                                    }else if(("").equals(uc.getBussinessModule())&&(uc.hasFun("LOANSWYBEF")||uc.hasFun("LOANSWYBSC")||uc.hasFun("LOANSWYBAR"))){
                                    
      out.write("\r\n");
      out.write("                                    <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/loanerrhint.jsp\"><u>");
      out.print(LoanErrHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												//if (("EF").equals(uc.getBussinessModule()) || ("SC").equals(uc.getBussinessModule())
												//|| ("AR").equals(uc.getBussinessModule())
												//|| ("").equals(uc.getBussinessModule())) {
											if((uc.hasFun("ZDMHSBEF")||uc.hasFun("ZDJXEF"))){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/exphint.jsp\"><u>");
      out.print(ExpHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if((uc.hasFun("ZDMHSC")||uc.hasFun("ZDJXSC"))){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/exphint.jsp\"><u>");
      out.print(ExpHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");

                                    }else if((uc.hasFun("ZDMHAR")||uc.hasFun("ZDJXAR"))){
                                    
      out.write("\r\n");
      out.write("                                    <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/exphint.jsp\"><u>");
      out.print(ExpHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 
									}else if(("").equals(uc.getBussinessModule())&&(uc.hasFun("ZDMHSBEF")||uc.hasFun("ZDJXEF")||uc.hasFun("ZDMHSC")||uc.hasFun("ZDJXSC")||uc.hasFun("ZDMHAR")||uc.hasFun("ZDJXAR"))){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/exphint.jsp\"><u>");
      out.print(ExpHint);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.3]  [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												//if (("EF").equals(uc.getBussinessModule()) || ("IF").equals(uc.getBussinessModule())
												//|| ("SC").equals(uc.getBussinessModule())
												//|| ("AR").equals(uc.getBussinessModule())
												//|| ("").equals(uc.getBussinessModule())) {
									  if((uc.hasFun("CLBDUESELLEREF")||uc.hasFun("CLBDUEBUYEREF")||uc.hasFun("CLBDUEMSEF")||uc.hasFun("CLBDUEIMPEF"))){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/clbinfo.jsp\"><u>");
      out.print(EXPIRYDATE);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
 
                                    }else if((uc.hasFun("CLBDUEBUYEREF")||uc.hasFun("CLBDUEIMPEF")||uc.hasFun("CLBDUEIFMS"))){
                                    
      out.write("\r\n");
      out.write("                                    <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/clbinfo.jsp\"><u>");
      out.print(EXPIRYDATE);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if((uc.hasFun("CLBDUESELLEREF")||uc.hasFun("CLBDUEBUYEREF")||uc.hasFun("CLBDUEIMPEF"))){ 
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/clbinfo.jsp\"><u>");
      out.print(EXPIRYDATE);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if((uc.hasFun("CLBDUEIMPEF")||uc.hasFun("CLBSELLAR"))){ 
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/clbinfo.jsp\"><u>");
      out.print(EXPIRYDATE);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if((uc.hasFun("CLBDUESELLEREF")||uc.hasFun("CLBDUEBUYEREF")||uc.hasFun("CLBDUEMSEF")||uc.hasFun("CLBDUEIMPEF")||uc.hasFun("CLBDUEIFMS")||uc.hasFun("CLBSELLAR"))){ 
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/clbinfo.jsp\"><u>");
      out.print(EXPIRYDATE);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("                                    ");
 
                                    }
                                    
      out.write("\r\n");
      out.write("                                    <!-- [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												//if (("EF").equals(uc.getBussinessModule()) || ("IF").equals(uc.getBussinessModule())
												//|| ("").equals(uc.getBussinessModule())) {
										if((uc.hasFun("BOPERROR")||uc.hasFun("BOPMZINFOR"))){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/bop.jsp\"><u>");
      out.print(BopQuery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if((uc.hasFun("BOPERROR")||uc.hasFun("BOPMZINFOR"))){ 
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/bop.jsp\"><u>");
      out.print(BopQuery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else if(("").equals(uc.getBussinessModule())&&(uc.hasFun("BOPERROR")||uc.hasFun("BOPMZINFOR"))){ 
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/bop.jsp\"><u>");
      out.print(BopQuery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--[1.4] start  toby add -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--动产质押授信业务提醒-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											if (("CMF").equals(uc.getBussinessModule()) || ("").equals(uc.getBussinessModule())) {
											if (uc.hasFun("CMFJGTX")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR class=\"rownormal\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/cmfremind.jsp\"><u>");
      out.print(cmfcreditremind);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
								//[1.8] begin
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/queryreastorageamtinfo.jsp\"><u>");
      out.print(cmfreaclbquery);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t");

							//[1.8] end
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--预付款融资业务提醒-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- [1.6]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											if (("POWF").equals(uc.getBussinessModule()) || ("").equals(uc.getBussinessModule())) {
											
											if (uc.hasFun("POWFJGTX")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR height=\"30\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<A href=\"../menu/powfremind.jsp\"><u>");
      out.print(powfloanremind);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</u>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--  gong gao lan-->\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TABLE class=\"mainBox\" cellSpacing=\"1\" cellPadding=\"2\" width=\"151\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR   class=\"rownormal\" align=\"middle\" height=\"30\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD  colSpan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SPAN style=\"font-weight:bold;\">");
      out.print(message.getMessage("FLD_SYS_BOARD"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR align=\"middle\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD colSpan=\"3\" height=\"160\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SPAN class=\"style4\"> ");
      out.print(VteamSystemNote);
      out.write(" </SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR   class=\"rownormal\" align=\"middle\" height=\"30\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD  colSpan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SPAN style=\"font-weight:bold;\">");
      out.print(message.getMessage("跑马灯信息"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR align=\"middle\" class=\"rownormal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD colSpan=\"3\" height=\"160\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SPAN class=\"style4\"> ");
      out.print(beltlignt_desc);
      out.write(" </SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- gong gao lan end-->\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<TABLE class=\"normal\" cellSpacing=\"0\" cellPadding=\"0\" width=\"70%\"\r\n");
      out.write("\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"4\" colspan=\"4\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t");

							if ("zh_TW".equals(locale.toString())) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;");
      out.print(message.getMessage("LBL_XTSHUOM") );
      out.write("：\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t1.");
      out.print(message.getMessage("LBL_LWSHUOMING") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t2.");
      out.print(message.getMessage("LBL_XTBJ") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t3.");
      out.print(message.getMessage("LBL_DQBANBEN") );
      out.write("：\r\n");
      out.write("\t\t\t\t\t\t\t");

							} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;");
      out.print(message.getMessage("LBL_XTSHUOM") );
      out.write("：\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t1.");
      out.print(message.getMessage("LBL_LWSHUOMING") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t2.");
      out.print(message.getMessage("LBL_XTBJ") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t3.");
      out.print(message.getMessage("LBL_DQBANBEN") );
      out.write("：\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t[2011-05-03]\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<TABLE class=\"normal\" cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD vAlign=\"top\" align=\"right\" height=\"0\">\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<TABLE class=\"normal\" cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<TR class=\"mainbg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD colSpan=\"2\" height=\"26\" align=\"middle\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<A class=\"mainbg\" href=\"../menu/techsupport.jsp\"  >");
      out.print(message.getMessage("LBL_SUPPORT"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</A> |\r\n");
      out.write("\t\t\t\t\t\t\t<A class=\"mainbg\" href=\"http://www.vteamsystem.com.cn/\" target=\"_blank\">");
      out.print(message.getMessage("LBL_CONTACTUS"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</A>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD colSpan=\"3\" height=\"0\"></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD colSpan=\"3\" height=\"15\">\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(message.getMessage("LBL_COPYRIGHT"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
