/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-25 04:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class middle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<HTML><HEAD><TITLE>middlepage</TITLE>\r\n");
      out.write("<STYLE type=text/css>\r\n");
      out.write(".pointer {\r\n");
      out.write("cursor:pointer\r\n");
      out.write("}\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function Submit_onclick(){\r\n");
      out.write("   if(window.parent.document.getElementById(\"indexFrame\").cols==\"200,7,*\"){\r\n");
      out.write("\t\twindow.parent.document.getElementById(\"indexFrame\").cols=\"0,7,*\";\r\n");
      out.write("\t\tdocument.getElementById(\"switchbar\").src=\"../images/rightMove.gif\";\r\n");
      out.write("\t\tdocument.getElementById(\"buttonLink\").title=\"显示菜单栏\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\twindow.parent.document.getElementById(\"indexFrame\").cols=\"200,7,*\";\r\n");
      out.write("\t\tdocument.getElementById(\"switchbar\").src=\"../images/leftMove.gif\";\r\n");
      out.write("\t\tdocument.getElementById(\"buttonLink\").title=\"隐藏菜单栏\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<script language=\"JavaScript\" src=\"../jscript/submit.js\"></script>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<body leftmargin=\"0\" topmargin=\"0\"  onkeydown=\"javascript:closeIEkey();\" oncontextmenu=\"javascript:closeRightKey();\">\r\n");
      out.write("<table style=\"cursor:e-resize\" class=\"pointer\" width=\"100%\" height=\"100%\" background=\"../images/splitor7.gif\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"center\" valign=\"middle\" id=\"buttonLink\"><img id=\"switchbar\" class=\"pointer\" src=\"../images/rightMove.gif\" width=\"7\" height=\"54\" onClick=\"javascript:Submit_onclick();\" title=\"弹入/弹出\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body></HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
