//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string BTN_ADD_ROW {
            get {
                return ResourceManager.GetString("BTN_ADD_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BTN_BACK {
            get {
                return ResourceManager.GetString("BTN_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Top.
        /// </summary>
        internal static string BTN_BACK_TOP {
            get {
                return ResourceManager.GetString("BTN_BACK_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string BTN_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BTN_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Seller.
        /// </summary>
        internal static string BTN_CONTACT_SELLER {
            get {
                return ResourceManager.GetString("BTN_CONTACT_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BTN_EDIT {
            get {
                return ResourceManager.GetString("BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import xls data.
        /// </summary>
        internal static string BTN_IMPORT {
            get {
                return ResourceManager.GetString("BTN_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string BTN_IMPORT_FILE {
            get {
                return ResourceManager.GetString("BTN_IMPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquire.
        /// </summary>
        internal static string BTN_QUERY {
            get {
                return ResourceManager.GetString("BTN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string BTN_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("BTN_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string BTN_SUBMIT {
            get {
                return ResourceManager.GetString("BTN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age(Day).
        /// </summary>
        internal static string FLD_AGE {
            get {
                return ResourceManager.GetString("FLD_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string FLD_COLOR {
            get {
                return ResourceManager.GetString("FLD_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string FLD_COMFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("FLD_COMFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        internal static string FLD_CREATE_DATE {
            get {
                return ResourceManager.GetString("FLD_CREATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string FLD_CREATE_USER {
            get {
                return ResourceManager.GetString("FLD_CREATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string FLD_CUST_NAME {
            get {
                return ResourceManager.GetString("FLD_CUST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        internal static string FLD_DEALER {
            get {
                return ResourceManager.GetString("FLD_DEALER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Time.
        /// </summary>
        internal static string FLD_EDIT_DATE {
            get {
                return ResourceManager.GetString("FLD_EDIT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string FLD_EDIT_USER {
            get {
                return ResourceManager.GetString("FLD_EDIT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string FLD_EMAIL {
            get {
                return ResourceManager.GetString("FLD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FLD_FIRST_NAME {
            get {
                return ResourceManager.GetString("FLD_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        internal static string FLD_GROUP_ID {
            get {
                return ResourceManager.GetString("FLD_GROUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string FLD_GROUP_NAME {
            get {
                return ResourceManager.GetString("FLD_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Use.
        /// </summary>
        internal static string FLD_GROUP_USE {
            get {
                return ResourceManager.GetString("FLD_GROUP_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string FLD_IS_CHECKED {
            get {
                return ResourceManager.GetString("FLD_IS_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string FLD_LAST_NAME {
            get {
                return ResourceManager.GetString("FLD_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length(Meters).
        /// </summary>
        internal static string FLD_LENGTH_METER {
            get {
                return ResourceManager.GetString("FLD_LENGTH_METER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number.
        /// </summary>
        internal static string FLD_LOT {
            get {
                return ResourceManager.GetString("FLD_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string FLD_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("FLD_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string FLD_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("FLD_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core size.
        /// </summary>
        internal static string FLD_PACKAGE {
            get {
                return ResourceManager.GetString("FLD_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string FLD_PASSWORD {
            get {
                return ResourceManager.GetString("FLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string FLD_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("FLD_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(Roll).
        /// </summary>
        internal static string FLD_QTY {
            get {
                return ResourceManager.GetString("FLD_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string FLD_REGION {
            get {
                return ResourceManager.GetString("FLD_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FLD_SPEC {
            get {
                return ResourceManager.GetString("FLD_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FLD_STATUS {
            get {
                return ResourceManager.GetString("FLD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FLD_UM {
            get {
                return ResourceManager.GetString("FLD_UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string FLD_USER_ID {
            get {
                return ResourceManager.GetString("FLD_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string FLD_USER_NAME {
            get {
                return ResourceManager.GetString("FLD_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width(mm).
        /// </summary>
        internal static string FLD_WIDTH_MM {
            get {
                return ResourceManager.GetString("FLD_WIDTH_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Magnification Setting.
        /// </summary>
        internal static string FUN_AREA_MAGNIFICATION {
            get {
                return ResourceManager.GetString("FUN_AREA_MAGNIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Parameter Setting.
        /// </summary>
        internal static string FUN_AREA_PARAMETER {
            get {
                return ResourceManager.GetString("FUN_AREA_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Parameter Setting.
        /// </summary>
        internal static string FUN_CATEGORY_PARAMETER {
            get {
                return ResourceManager.GetString("FUN_CATEGORY_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Parameter Setting.
        /// </summary>
        internal static string FUN_FORMULA_PARAMETER {
            get {
                return ResourceManager.GetString("FUN_FORMULA_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Setting.
        /// </summary>
        internal static string FUN_GROUP_SETTING {
            get {
                return ResourceManager.GetString("FUN_GROUP_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Query.
        /// </summary>
        internal static string FUN_HISTORY_QUERY {
            get {
                return ResourceManager.GetString("FUN_HISTORY_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management.
        /// </summary>
        internal static string FUN_LOGISTICS_MANAGE {
            get {
                return ResourceManager.GetString("FUN_LOGISTICS_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setting.
        /// </summary>
        internal static string FUN_MASTER_SETTING {
            get {
                return ResourceManager.GetString("FUN_MASTER_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preceding Parameter.
        /// </summary>
        internal static string FUN_PRECEDING_PARAMETER {
            get {
                return ResourceManager.GetString("FUN_PRECEDING_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Magnification Setting.
        /// </summary>
        internal static string FUN_QUANTITY_MAGNIFICATION {
            get {
                return ResourceManager.GetString("FUN_QUANTITY_MAGNIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Setting.
        /// </summary>
        internal static string FUN_SECURITY_SETTING {
            get {
                return ResourceManager.GetString("FUN_SECURITY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Import.
        /// </summary>
        internal static string FUN_STOCK_SHARE_ENTRY {
            get {
                return ResourceManager.GetString("FUN_STOCK_SHARE_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Search.
        /// </summary>
        internal static string FUN_STOCK_SHARE_SEARCH {
            get {
                return ResourceManager.GetString("FUN_STOCK_SHARE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Setting.
        /// </summary>
        internal static string FUN_SYSTEM_PARAMETER {
            get {
                return ResourceManager.GetString("FUN_SYSTEM_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        internal static string FUN_SYSTEM_SETTING {
            get {
                return ResourceManager.GetString("FUN_SYSTEM_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setting.
        /// </summary>
        internal static string FUN_USER_SETTING {
            get {
                return ResourceManager.GetString("FUN_USER_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Europe.
        /// </summary>
        internal static string FUN_WESTERN_EUROPE {
            get {
                return ResourceManager.GetString("FUN_WESTERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string LBL_AVAILABLE {
            get {
                return ResourceManager.GetString("LBL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string LBL_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string LBL_CHECKED {
            get {
                return ResourceManager.GetString("LBL_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string LBL_CHECK_ALL {
            get {
                return ResourceManager.GetString("LBL_CHECK_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string LBL_COLOR {
            get {
                return ResourceManager.GetString("LBL_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string LBL_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string LBL_GROUP_NAME {
            get {
                return ResourceManager.GetString("LBL_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string LBL_INDEX {
            get {
                return ResourceManager.GetString("LBL_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string LBL_INQUIRY {
            get {
                return ResourceManager.GetString("LBL_INQUIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LBL_LOGOUT {
            get {
                return ResourceManager.GetString("LBL_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string LBL_PAGE {
            get {
                return ResourceManager.GetString("LBL_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string LBL_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("LBL_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string LBL_USER_ID {
            get {
                return ResourceManager.GetString("LBL_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string LBL_USER_NAME {
            get {
                return ResourceManager.GetString("LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string LBL_USER_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account and Email not matching..
        /// </summary>
        internal static string MSG_ACCOUNT_EMAIL_NOT_MACHING {
            get {
                return ResourceManager.GetString("MSG_ACCOUNT_EMAIL_NOT_MACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your creation is failed.
        /// </summary>
        internal static string MSG_ADD_FAIL {
            get {
                return ResourceManager.GetString("MSG_ADD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your creation is successful.
        /// </summary>
        internal static string MSG_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check email we sent. Your New Password Is.
        /// </summary>
        internal static string MSG_CHECK_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_CHECK_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete all selected items.
        /// </summary>
        internal static string MSG_CONFIRM_DELETE_ITEM {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deletion is failed.
        /// </summary>
        internal static string MSG_DELETE_FAIL {
            get {
                return ResourceManager.GetString("MSG_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deletion is successful.
        /// </summary>
        internal static string MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your edition is failed.
        /// </summary>
        internal static string MSG_EDIT_FAIL {
            get {
                return ResourceManager.GetString("MSG_EDIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your edition is successful.
        /// </summary>
        internal static string MSG_EDIT_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_EDIT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record.
        /// </summary>
        internal static string MSG_FIRST_RECORD {
            get {
                return ResourceManager.GetString("MSG_FIRST_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string MSG_INPUT_ERROR {
            get {
                return ResourceManager.GetString("MSG_INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string MSG_INQUIRY {
            get {
                return ResourceManager.GetString("MSG_INQUIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}must be entered.
        /// </summary>
        internal static string MSG_IS_NEED_ITEM {
            get {
                return ResourceManager.GetString("MSG_IS_NEED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing.
        /// </summary>
        internal static string MSG_LOADING {
            get {
                return ResourceManager.GetString("MSG_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have signed in as {0}.
        /// </summary>
        internal static string MSG_LOGIN_USER {
            get {
                return ResourceManager.GetString("MSG_LOGIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}character as mimum is required.
        /// </summary>
        internal static string MSG_MINIMUN_LENGTH {
            get {
                return ResourceManager.GetString("MSG_MINIMUN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is incorrect.
        /// </summary>
        internal static string MSG_PASSWORD_NOT_EQUAL {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user name is not activated.
        /// </summary>
        internal static string MSG_USER_INACTIVE {
            get {
                return ResourceManager.GetString("MSG_USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not exist..
        /// </summary>
        internal static string MSG_USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password is incorrect.
        /// </summary>
        internal static string MSG_USER_PASSWORD_ERR {
            get {
                return ResourceManager.GetString("MSG_USER_PASSWORD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        internal static string TIT_ACCOUNT_MANAGE {
            get {
                return ResourceManager.GetString("TIT_ACCOUNT_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string TIT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("TIT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TIT_LOGIN {
            get {
                return ResourceManager.GetString("TIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; Group Setting ─&gt; Delete.
        /// </summary>
        internal static string TIT_SECURITY_GROUP_DELETE {
            get {
                return ResourceManager.GetString("TIT_SECURITY_GROUP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; Group Setting ─&gt; Edit.
        /// </summary>
        internal static string TIT_SECURITY_GROUP_EDIT {
            get {
                return ResourceManager.GetString("TIT_SECURITY_GROUP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; Group Setting.
        /// </summary>
        internal static string TIT_SECURITY_GROUP_MAIN {
            get {
                return ResourceManager.GetString("TIT_SECURITY_GROUP_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; Group Setting ─&gt; Create new.
        /// </summary>
        internal static string TIT_SECURITY_GROUP_NEW {
            get {
                return ResourceManager.GetString("TIT_SECURITY_GROUP_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; Group Setting ─&gt; Search.
        /// </summary>
        internal static string TIT_SECURITY_GROUP_QUERY {
            get {
                return ResourceManager.GetString("TIT_SECURITY_GROUP_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; User ─&gt; Delete.
        /// </summary>
        internal static string TIT_SECURITY_USER_DELETE {
            get {
                return ResourceManager.GetString("TIT_SECURITY_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; User ─&gt; Edit.
        /// </summary>
        internal static string TIT_SECURITY_USER_EDIT {
            get {
                return ResourceManager.GetString("TIT_SECURITY_USER_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; User.
        /// </summary>
        internal static string TIT_SECURITY_USER_MAIN {
            get {
                return ResourceManager.GetString("TIT_SECURITY_USER_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; User ─&gt; Create new.
        /// </summary>
        internal static string TIT_SECURITY_USER_NEW {
            get {
                return ResourceManager.GetString("TIT_SECURITY_USER_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting ─&gt; Security Setting ─&gt; User ─&gt; Search.
        /// </summary>
        internal static string TIT_SECURITY_USER_QUERY {
            get {
                return ResourceManager.GetString("TIT_SECURITY_USER_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt; Stock Sharing Import ─&gt; delete.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_DELETE {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt; Stock Sharing Import ─&gt; Edit.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_EDIT {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Import ─&gt; xls Import.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_IMPORT {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Import.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_MAIN {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Import ─&gt; Create new.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_NEW {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Import ─&gt; Search.
        /// </summary>
        internal static string TIT_STOCK_ENTRY_QUERY {
            get {
                return ResourceManager.GetString("TIT_STOCK_ENTRY_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Search.
        /// </summary>
        internal static string TIT_STOCK_SEARCH_MAIN {
            get {
                return ResourceManager.GetString("TIT_STOCK_SEARCH_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Sharing Management ─&gt; Western Europe ─&gt;  Stock Sharing Search ─&gt; Search.
        /// </summary>
        internal static string TIT_STOCK_SEARCH_QUERY {
            get {
                return ResourceManager.GetString("TIT_STOCK_SEARCH_QUERY", resourceCulture);
            }
        }
    }
}
