/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-25 04:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import control.UserControl;
import vteam.frame.system.sysconst.FrameConst;
import vteam.frame.system.exception.*;
import vteam.csps.common.MessageConst;
import vteam.csps.common.BussConst;
import vteam.web.query.BussOperQuery;
import vteam.web.query.BussForeQuery;
import vteam.csps.security.sc.SCBankUser;
import vteam.frame.system.message.MessageResourceImpl;
import vteam.web.query.QueryByPK;
import vteam.common.tools.data.ProcessDataSet;
import java.util.Locale;
import vteam.common.tools.util.ChkMethod;
import vteam.web.menu.*;
import java.util.Vector;

public final class title_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	response.setHeader("Expires","Tues,01 Jan 1980 00:00:00 GMT");
	UserControl uc = new UserControl(session);
        Locale locale = uc.getLocale();
       if(uc.getUserID() == null){//修改session失效后刷新,title页面报错问题 //20071107
          return;
        }

    	String language = uc.getLocale().toString();

	String logouturl = "../dobusiness.do?"+FrameConst.ACTION_ID+"="+FrameConst.ACTION_LOGOUT;

        //获取多语言
        MessageResourceImpl message = MessageResourceImpl.getInstance();
        message.setLanLocal(uc.getLocale());

        //String pic01 = "../images/logo_h63.gif";
        String pic01 = "../images/logo_h262.gif";
        //System.out.println("userid 1 " + uc.getUserID());
        String userid = uc.getUserID();
        //System.out.println("userid 2 " + uc.getUserID());

        String username = "";
        String deptid = "";
        String bchdesc = "";
        String bchid = "";
        String week = "";
        BussForeQuery bfquery = new BussForeQuery();
      try{
        if(userid != null){
        	QueryByPK q = new QueryByPK();
        	
        	ProcessDataSet userPds = q.findSIPABURMByPK(userid);
        	if(userPds != null && userPds.size() > 0){
        		username = userPds.getString("USERNAME");
        		deptid = userPds.getString("DEPTID");
        		bchid=userPds.getString("BCHID");
        	}
        	
            
        	if(bchid != null){
            	QueryByPK qpk = new QueryByPK();
            	ProcessDataSet bchpds = qpk.findFIPABCHMByPK(bchid);
                if(bchpds != null && bchpds.size() > 0){
                    bchpds.start();
                    bchpds.next();
                    bchdesc = bchpds.getString("BCHDESC");
                }
            }
        	
        	if(deptid != null && !deptid.equals("")){
        		ProcessDataSet dptPds = q.findFIPADPTMByPK(deptid);
        		if(dptPds != null && dptPds.size() > 0){
        			deptid = dptPds.getString("DEPTDESC");
        		}
        	}
        }
      //星期   
        
        int day = bfquery.getBussDate().getDate("PARAMVALUE").getDay();
        
        if(0==day){
        		week = "星期日";
        }else if(1==day){
        		week = "星期一";
        }else if(2==day){
        		week = "星期二";
        }else if(3==day){
        		week = "星期三";
        }else if(4==day){
        		week = "星期四";
        }else if(5==day){
        		week = "星期五";
        }else if(6==day){
        		week = "星期六";
        }
      }catch(Exception e){

      }

      //Generate Mul-Language Array for JS
      String[] allJSMul = new String[]{
        //dateselect.js
            "MSG_OBJNO_EXIST", //控制对象不存在1！
            "MSG_INCOMNO_APPOINT", //输入控件未指定2！
            "MSG_INCOMNO_EXIST", //输入控件不存在3！
            "MSG_INCOMTYPE_ERR", //输入控件类型错误！
            "MSG_COMNO_EXIST", //参考控件不存在4！
            "MSG_COMTYPE_ERR", //参考控件类型错误！
            "MSG_DATELOAD_FAIL", //日历未成功装载！请刷新页面！
            "MSG_DATETYPE_ERR", //日期格式非法
            "MSG_NUMTYPE_ERR", //数字格式非法
        //submit.js
            "MSG_SUBTWICE", //禁止重复提交！
            "MSG_PAGENULL", //页数不能为空!
            "MSG_SUBMIT", //确定提交?
            "MSG_LOANAMTS_SMALL", //本次融资总额不能小于零。
            "MSG_LOANAMTS_OVER", //本次融资总额超过了融资金额之和。
            "MSG_RZPAIDAMT_SMALL", //还融资总额不能小于零。
            "MSG_RZPAIDAMT_OVER", //还融资总额超过了所有融资余额之和。
            "EOR_CHO_REC", //[1.0]请选择要操作的记录。
            "EOR_T_REGCOUNTS_D_ZERO",//[1.3]本次补货数量不能小于零
       //format.js     
            "EOR_NOT_EXCESS",//[1.4]输入的金额栏位字符长度不能超过12位!
      //dailytask.jsp      
            "MSG_DT_EXIT_LOAN"//[1.5]存在未放行的受让的资料,是否继续?
    }; //COLID
      StringBuffer jsBuff = new StringBuffer();
      if(allJSMul != null){
        String currmul ;
        for(int i = 0; i < allJSMul.length; i++){
          currmul = "mulArray[" + i + "]";
          jsBuff.append(currmul).append(" = new Array();")
          .append(currmul).append("[0]=\"").append(allJSMul[i]).append("\";")
          .append(currmul).append("[1]=\"").append(message.getMessage(allJSMul[i])).append("\";");
        }
      }
      
   SCBankUser bankuser = new SCBankUser();
   Vector vfun = bankuser.findFunIDByUserID(userid);
   TopMenu topmu = new TopMenu();
   //HashMap menuMap = topmu.getFullMenuMap(vfun,userid);
   HashMap map=uc.getMenuListScript();//从缓存获取菜单
   HashMap topMenuMap = (HashMap)map.get("topMenuMap");
   String menuScript = ((StringBuffer)topMenuMap.get("FullMenuBuffer")).toString();
   String topMenu = ((StringBuffer)topMenuMap.get("TopMenuBuffer")).toString();
  

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("  <script language=\"JavaScript\" src=\"../jscript/submit.js\"></script>\r\n");
      out.write("  <script language=\"JavaScript\" src=\"../jscript/arfp.js\"></script>\r\n");
      out.write("  <link href=\"../css/vteam.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("A:link{\r\n");
      out.write("\tFONT-SIZE: 9pt;\r\n");
      out.write("\tCOLOR: white;\r\n");
      out.write("        /*COLOR: #FF0000;*/\r\n");
      out.write("\tTEXT-DECORATION: none;\r\n");
      out.write("}\r\n");
      out.write("A:visited{\r\n");
      out.write("\tFONT-SIZE: 9pt;\r\n");
      out.write("\tCOLOR: white;\r\n");
      out.write("\tTEXT-DECORATION: none;\r\n");
      out.write("\t/*background-color: #00FFFF;*/\r\n");
      out.write("}\r\n");
      out.write("A:hover{\r\n");
      out.write("\tFONT-SIZE: 9pt;\r\n");
      out.write("\tCOLOR:white;\r\n");
      out.write("\tTEXT-DECORATION: none;\r\n");
      out.write("\t/*background-color: #FDF5E1;#ef4118 */\r\n");
      out.write("}\r\n");
      out.write("a.hover{FONT-SIZE: 12px; COLOR: #FF0000}\r\n");
      out.write(".style2 {\r\n");
      out.write("\tFONT-SIZE: 12px; COLOR: #000000\r\n");
      out.write("}\r\n");
      out.write(".style3 {\r\n");
      out.write("\tFONT-SIZE: 12px; COLOR: #FF0000\r\n");
      out.write("}\r\n");
      out.write("body,td,th {\r\n");
      out.write("\tFONT-SIZE: 12px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" <BODY leftMargin=\"0\" topMargin=\"0\" rightMargin=\"0\"  onkeydown=\"javascript:closeIEkey();\" oncontextmenu=\"javascript:closeRightKey();\" >\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" function toSubMenuSelect(){//luna temp\r\n");
      out.write(" \t\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("  function selectModule(module){//luna temp\r\n");
      out.write(" \t var menurowid_show = \"id_menu_\"+id1;\r\n");
      out.write("     var menurowid_hide = \"id_menu_\"+id2;\r\n");
      out.write("\t document.getElementById(menurowid_show).style.display=\"\";\r\n");
      out.write("\t document.getElementById(menurowid_hide).style.display=\"none\";\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function selectFunction(id1,id2){// luna temp\r\n");
      out.write(" \r\n");
      out.write("  var funcellid_sel = \"id_fun_\"+id1;\r\n");
      out.write("  var funcellid_unsel = \"id_fun_\"+id2;\r\n");
      out.write("  document.getElementById(funcellid_sel).style.backgroundColor=\"#6392C6\";\r\n");
      out.write("  document.getElementById(funcellid_unsel).style.backgroundColor=\"#F3F3F3\";\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("function showFunList(){\r\n");
      out.write("    var selwinfeatures = \"width=550,height=600,top=60,left=250,resizable=no,status=no,scrollbars=yes,titlebar=no,toolbar=no,menubar=no,location=no\";\r\n");
      out.write("    window.open(\"../sysmanage/sysmanage.jsp\",\"_blank\",selwinfeatures);\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("function selectGuidemap(){\r\n");
      out.write("\tvar urlsel = \"../guidemap/selectguidemap.jsp\";\r\n");
      out.write("    var selwinfeatures = \"Height=330px,Width=500px,Top=235px,Left=240px,resizable=no,status=no,scrollbars=no,titlebar=no,toolbar=no,menubar=no,location=no\";\r\n");
      out.write(" \twindow.open(urlsel,\"\",selwinfeatures);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadAllMul(){\r\n");
      out.write(" var mulArray = new Array();\r\n");
      out.write(" ");
      out.print(jsBuff.toString());
      out.write("\r\n");
      out.write(" return mulArray;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" /***** 菜单样式定义 start ******/\r\n");
      out.write("var style_grpbasediv = \" border:1px solid #6893cf; background:url(../images/mainmenu/mainmenubg.gif) repeat-y left center #FFF\";\r\n");
      out.write("\r\n");
      out.write("var style_grpmaindiv =\"BACKGROUND-image:url(../images/head1.gif) repeat-y left center;background-position:2px center; background-repeat:no-repeat; clear:both; line-height:18px; height:18px; padding-left:5px; padding-right:4px; padding-top:2px; padding-bottom:1px; cursor:pointer; margin:1px; border:1px transparent\";\r\n");
      out.write("var style_grpspan =\"height:16px;width:16px;float:right;background:url(../images/head1.gif) 8px center no-repeat\";\r\n");
      out.write("var style_menulinkspan =\"font-size:12px\";\r\n");
      out.write("var style_mouseover =\"this.style.backgroundColor='#EFEFEF';this.style.border='1px solid #6893cf';\";\r\n");
      out.write("var style_mouseout = \"this.style.backgroundColor='transparent';this.style.border='1px transparent ';\";\r\n");
      out.write("/****** 菜单样式定义 end *******/\r\n");
      out.write("\r\n");
      out.write("var   defOver   =   '#336699',   defBack   =   '#003366';   \r\n");
      out.write("var   defLength   =   22;   \r\n");
      out.write("var menu = new Array();\r\n");
      out.print(menuScript);
      out.write("\r\n");
      out.write("function   Menu(isVert,   popInd,   x,   y,   width,   overCol,   backCol,   borderClass,   textClass)   {   \r\n");
      out.write("  //   True   or   false   -   a   vertical   menu?   \r\n");
      out.write("  this.isVert   =   isVert;   \r\n");
      out.write("  //   The   popout   indicator   used   (if   any)   for   this   menu.   \r\n");
      out.write("  this.popInd   =   popInd;   \r\n");
      out.write("  //   Position   and   size   settings.   \r\n");
      out.write("  this.x   =   x;   \r\n");
      out.write("  this.y   =   y;   \r\n");
      out.write("  this.width   =   width;   \r\n");
      out.write("  //   Colours   of   menu   and   items.   \r\n");
      out.write("  this.overCol   =   overCol;   \r\n");
      out.write("  this.backCol   =   backCol;   \r\n");
      out.write("  //   The   stylesheet   class   used   for   item   borders   and   the   text   within   items.   \r\n");
      out.write("  this.borderClass   =   borderClass;   \r\n");
      out.write("  this.textClass   =   textClass;   \r\n");
      out.write("  //   Parent   menu   and   item   numbers,   indexed   later.   \r\n");
      out.write("  this.parentMenu   =   null;   \r\n");
      out.write("  this.parentItem   =   null;   \r\n");
      out.write("  //   Reference   to   the   object's   style   properties   (set   later).   \r\n");
      out.write("  this.ref   =   null;   \r\n");
      out.write("  }   \r\n");
      out.write("  \r\n");
      out.write("  function   Item(text,   href,   frame,   length,   spacing,   target)   {   \r\n");
      out.write("  this.text   =   text;   \r\n");
      out.write("  this.href   =   href;   \r\n");
      out.write("  this.frame   =   frame;   \r\n");
      out.write("  this.length   =   length;   \r\n");
      out.write("  this.spacing   =   spacing;   \r\n");
      out.write("  this.target   =   target;   \r\n");
      out.write("  //   Reference   to   the   object's   style   properties   (set   later).   \r\n");
      out.write("  this.ref   =   null;   \r\n");
      out.write("  } \r\n");
      out.write(" \r\n");
      out.write("var pops = new Array(); // 用来存储Popup窗口家族的数组\r\n");
      out.write("function CreatePopup(degree)\r\n");
      out.write("{\r\n");
      out.write("  \r\n");
      out.write("\tif (degree < 0)\t// 层数不能小于0\r\n");
      out.write("\t\treturn null;\r\n");
      out.write("\tif (pops[degree] != null) //如果已经存在则不需创建\r\n");
      out.write("\t\treturn pops[degree];\r\n");
      out.write("\r\n");
      out.write("\tif (degree == 0)\r\n");
      out.write("\t\tpops[0] = window.createPopup(); //创建最顶层Popup窗口\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tif (pops[degree - 1] == null)\r\n");
      out.write("\t\t\tpops[degree - 1] = CreatePopup(degree - 1)\t//递归回溯从第一层开始创建\r\n");
      out.write("\t\tpops[degree] = pops[degree - 1].document.parentWindow.createPopup(); //从父Popup窗口创建子Popup窗口\r\n");
      out.write("\t}\r\n");
      out.write("\tpops[degree].document.body.setAttribute(\"degree\", degree);\r\n");
      out.write("\treturn pops[degree];\r\n");
      out.write("}\r\n");
      out.write("CreatePopup(1); //创建一个2层的Popup家族\r\n");
      out.write("//Creating the popup window object\r\n");
      out.write("var oPopup = pops[0];\r\n");
      out.write("var timer = null; \r\n");
      out.write("  \r\n");
      out.write("function HideSubMenu(levelnum)\r\n");
      out.write("{\r\n");
      out.write("\tClearTimer();\r\n");
      out.write("\ttimer = window.setTimeout(\"pops[\"+levelnum+\"].hide()\", 2000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function ClearTimer()\r\n");
      out.write("{\r\n");
      out.write("\tif (timer != null)\r\n");
      out.write("\t\twindow.clearTimeout(timer)\r\n");
      out.write("\ttimer = null;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var parentwidth;\r\n");
      out.write("function ShowSubMenu(obj,parentGrpIndex,parentMenuIndex)\r\n");
      out.write("{ //第二层菜单\r\n");
      out.write("\tClearTimer();\r\n");
      out.write("\tvar HtmlStr = \"\";\r\n");
      out.write("\tvar bufferStr = \"\";\r\n");
      out.write("\tvar targetNum = getTargetMenuIndex(parentGrpIndex,parentMenuIndex);\r\n");
      out.write("\tif(targetNum == 0) return;\r\n");
      out.write("\tif( menu[targetNum] == null){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar menulength = menu[targetNum].length;\r\n");
      out.write("\tvar textlength = 0;\r\n");
      out.write("\tfor(var i=1;i<menulength;i++){\r\n");
      out.write("\t\tbufferStr += \"<div  style='\"+style_grpmaindiv+\"'\";\r\n");
      out.write("\t\tvar text = menu[targetNum][i].text;\r\n");
      out.write("\t\tvar funpath = menu[targetNum][i].href;\r\n");
      out.write("\t\tvar action = text;\r\n");
      out.write("\t\tif(funpath != '' && funpath.length > 0){\r\n");
      out.write("\t\t\tbufferStr +=\" onmouseover=\\\"\"+style_mouseover+\"\\\" onmouseout=\\\"parent.parent.HideSubMenu(0);\"+style_mouseout+\"\\\" \";\r\n");
      out.write("\t\t\tbufferStr +=\"  onclick=\\\"parent.parent.parent.menu.location.href='\" + funpath  +\r\n");
      out.write("            \"';if(parent.parent.parent.document.getElementById('all').rows=='120,*'){parent.parent.parent.document.getElementById('all').rows='92,*';}else if(parent.parent.parent.document.getElementById('all').rows=='54,*'){parent.parent.parent.document.getElementById('all').rows='30,*';}\\\" >\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t    bufferStr += \" onmouseover=\\\"parent.parent.ClearTimer();\"+style_mouseover+\"\\\" onmouseout=\\\"parent.parent.HideSubMenu(0);\"+style_mouseout+\"\\\" >\";\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbufferStr += \"<span style='\"+style_menulinkspan+\"'>\"+text+\"</span></div>\";\r\n");
      out.write("\t\tif(text.length > textlength){\r\n");
      out.write("\t\t\ttextlength = text.length;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tbufferStr += \"</DIV>\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar width =  textlength * 12 + 25 +10;\r\n");
      out.write("\tvar height =  (menulength-1) * 22 + 5;\r\n");
      out.write("    var left = obj.offsetLeft+parentwidth-3;\r\n");
      out.write("    var top = obj.offsetTop-1;\r\n");
      out.write("    \r\n");
      out.write("    HtmlStr += \"<DIV style='\"+style_grpbasediv+\";width:\"+width+\"px'>\";\r\n");
      out.write("    HtmlStr += bufferStr;\r\n");
      out.write("    pops[1].document.body.innerHTML = HtmlStr; \r\n");
      out.write("    //屏蔽右键\r\n");
      out.write("\tpops[1].document.oncontextmenu=function() {\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("    pops[1].show(left, 0, width, height, obj);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" function richDropDown(grpindex,menuIndex){ \r\n");
      out.write("   var HtmlStr = \"\";\r\n");
      out.write("\tvar bufferStr = \"\";\r\n");
      out.write("\tvar targetNum = getTargetMenuIndex(grpindex,menuIndex);\r\n");
      out.write("\tvar menulength = menu[targetNum].length;\r\n");
      out.write("\tvar textlength = 0;\r\n");
      out.write("\tvar arrow;\r\n");
      out.write("\t//alert(\"menulength=\"+parent.parent.document.getElementById('all').rows);\r\n");
      out.write("\tfor(var i=1;i<menulength;i++){\r\n");
      out.write("\t\tvar text = menu[targetNum][i].text;\r\n");
      out.write("\t\tvar funpath = menu[targetNum][i].href;\r\n");
      out.write("\t\tvar popInd = menu[targetNum][i].popInd;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbufferStr += \"<DIV id='m\"+i+\"' style=\\\"\";\r\n");
      out.write("\t\tbufferStr +=style_grpmaindiv+\"\\\"\"+\";\";\r\n");
      out.write("\t\tif(funpath != '' && funpath.length > 0){\r\n");
      out.write("\t\t\tbufferStr +=\" onmouseover=\\\"\"+style_mouseover+\"\\\" onmouseout=\\\"parent.HideSubMenu(0);\"+style_mouseout+\"\\\" \";\r\n");
      out.write("\t\t\tbufferStr +=\" onclick=\\\"parent.parent.menu.location.href='\" + funpath  + \r\n");
      out.write("\t\t\t\"';\"+style_mouseover+\"if(parent.parent.document.getElementById('all').rows=='120,*'){parent.parent.document.getElementById('all').rows='92,*';}else if(parent.parent.document.getElementById('all').rows=='54,*'){parent.parent.document.getElementById('all').rows='30,*';};\\\" >\";\r\n");
      out.write("\t\t\tarrow =\"\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t//\tbufferStr +=\" onmouseover=\\\"parent.ShowSubMenu(this,\"+targetNum+\",\"+i+\");\"+style_mouseover+\"\\\" onmouseout=\\\"parent.HideSubMenu(0);\"+style_mouseout+\"\\\"  onclick=\\\"parent.ShowSubMenu(this,\"+targetNum+\",\"+i+\");\"+style_mouseover+\"\\\">\";\r\n");
      out.write("\t\t//\tarrow = \"<img src=\\\"../images/mainmenu/arrow.gif\\\" align=\\\"right\\\"/>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbufferStr += arrow+\"<span style='\"+style_menulinkspan+\"'>\"+text+\"</span>\";\r\n");
      out.write("\t\tif(text.length > textlength){\r\n");
      out.write("\t\t\ttextlength = text.length;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//bufferStr += \"<span style=\\\"width=10px;height:10px;float:right\\\">\"+arrow+\"</span>\";\r\n");
      out.write("\t\tbufferStr +=\"</DIV>\";\r\n");
      out.write("\t}\r\n");
      out.write("\tbufferStr += \"</DIV>\";\r\n");
      out.write("\tvar width = textlength * 12 + 25 + 10;\r\n");
      out.write("\tparentwidth = width;\r\n");
      out.write("\tHtmlStr += \"<DIV style='\"+style_grpbasediv+\";width:\"+width+\"px'>\";\r\n");
      out.write("\tHtmlStr += bufferStr;\r\n");
      out.write("\t\r\n");
      out.write("\toPopup.document.body.innerHTML = HtmlStr;\r\n");
      out.write("\t//屏蔽右键\r\n");
      out.write("\toPopup.document.oncontextmenu=function() {\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar dropdownno = 'dropdowno' + menuIndex;\r\n");
      out.write("\tvar objdrop = document.getElementById(dropdownno);\r\n");
      out.write("\t\r\n");
      out.write("\tvar height = (menulength-1) * 22 + 5;//(menulength-1) * 22 + 5\r\n");
      out.write("\toPopup.show(10, 20, width, height, objdrop); \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("function getTargetMenuIndex(grpid,index){\r\n");
      out.write("\tif(menu[grpid] ==null || menu[grpid][index] == null){\r\n");
      out.write("\t\treturn -1;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar targetNum = menu[grpid][index].target;\r\n");
      out.write("\treturn targetNum;\r\n");
      out.write("}\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"form1\" id=\"form1\" method=\"post\">\r\n");
      out.write("<TABLE cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" border=\"0\" class=\"normal\" background=\"../images/logo2.gif\">\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t\t<TD width=\"300\"><IMG src=\"");
      out.print(pic01);
      out.write("\"></TD>\r\n");
      out.write("  \t\t <TD width=\"5%\"></TD>\r\n");
      out.write("  \t\t<!--<TD width=\"100\"></TD> -->\r\n");
      out.write("  \t\t<!--<td width=\"100\"></td>-->\r\n");
      out.write("  \t\t<td>\r\n");
      out.write("  \t\t<table>\r\n");
      out.write("  \t\t<tr>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<TD style=\"float:right; line-height:200%; margin:4px 24px; padding:0px 16px;border: 1px solid #666666;\">\r\n");
      out.write("               ");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(0,4));
      out.write("&nbsp;年&nbsp;");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(5,7));
      out.write("&nbsp;月&nbsp;");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(8,10));
      out.write("&nbsp;日&nbsp;\r\n");
      out.write("\t\t\t\t");
      out.print(week);
      out.write(" &nbsp;|&nbsp;\r\n");
      out.write("               ");
      out.print(message.getMessage("FLD_OWNBCH"));
      out.write(":&nbsp;");
      out.print(bchdesc);
      out.write("\r\n");
      out.write("                &nbsp;|&nbsp;\r\n");
      out.write("                ");
      out.print(message.getMessage("FLD_OWNDEPT"));
      out.write(":&nbsp;");
      out.print(deptid);
      out.write("\r\n");
      out.write("                &nbsp;|&nbsp;\r\n");
      out.write("               \r\n");
      out.write("\t\t\t  \t");
      out.print(message.getMessage("LBL_USER"));
      out.write("\r\n");
      out.write("                  ");

                   if(userid!=null) out.print(username);
                  
      out.write("\r\n");
      out.write("         </TD>\r\n");
      out.write("         </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         </td>\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("        </TBODY>\r\n");
      out.write(" </TABLE>\r\n");
      out.write("\r\n");
      out.write("<TABLE style=\"color: white\"cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" background=\"../images/topmenu1/menu_bg.gif\" border=\"0\"><!-- ../images/framevork_05.gif -->\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD>\r\n");
      out.write("            <TABLE style=\"color: white\" cellSpacing=\"0\" cellPadding=\"0\" border=\"0\" width=\"680\" >\r\n");
      out.write("              <TBODY>\r\n");
      out.write("              <TR>\r\n");
      out.write("                \r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <td>\r\n");
      out.write("                ");
      out.print(topMenu );
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                \r\n");
      out.write("              </TR></TBODY></TABLE></TD>\r\n");
      out.write("              <TD style=\"font-size: 9pt\" align=\"center\" >\r\n");
      out.write("              <!-- ");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(0,4));
      out.write("&nbsp;年\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(5,7));
      out.write("&nbsp;月\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(bfquery.getBussDate().getString("PARAMVALUE").substring(8,10));
      out.write("&nbsp;日&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(week);
      out.write(" \r\n");
      out.write("\t\t\t  -->\r\n");
      out.write("\t\t\t  <TABLE style=\"color: white\" cellSpacing=\"0\" cellPadding=\"0\" border=\"0\">\r\n");
      out.write("                    <TBODY>\r\n");
      out.write("                    <TR>\r\n");
      out.write("                      <TD >");
      out.write("</TD>\r\n");
      out.write("                      <TD >&nbsp;&nbsp;<A href=\"../main/index.jsp\" target=\"_parent\">\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        ");
      out.print(message.getMessage("BTN_FIRSTPAGE"));
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("\r\n");
      out.write("                      <TD >");
      out.write("</TD>\r\n");
      out.write("                      <TD >&nbsp;&nbsp;<A href=\"../main/modpwd.jsp\" target=\"view\">\r\n");
      out.write("                        <!--IMG height=\"13\" src=\"../images/menu_index08.gif\" width=\"50\" border=\"0\"-->\r\n");
      out.write("                        ");
      out.print(message.getMessage("INI_EDT_CHG_PWD"));
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("                     \r\n");
      out.write("                      <!-- toby add 20090302 [1.2] -->\r\n");
      out.write("                       ");
 
                       String url=null;
                       String module = uc.getBussinessModule();
                       if(ChkMethod.isBlank(module)){
                    	   url="selectGuidemap";
                       }else if("EF".equals(module)){
                    	   url="../guidemap/efguidemap.jsp";
                       }else if("IF".equals(module)){
                    	   url="../guidemap/ifguidemap.jsp";
                       }else if("SC".equals(module)){
                    	   url="../guidemap/scguidemap.jsp";
                       }else if("AR".equals(module)){
                    	   url="../guidemap/arfpguidemap.jsp";
                       }else if("CMF".equals(module)){
                    	   url="../guidemap/cmfguidemap.jsp";
                       }else if("POWF".equals(module)){
                    	   url="../guidemap/powfguidemap.jsp";
                       }
                      //安控 联贷 基础参数 不显示导航图按钮
                      if(!("SPA".equals(module)||"IPAS".equals(module)||"STS".equals(module))){
      out.write("\r\n");
      out.write("                      <TD >");
      out.write("</TD>\r\n");
      out.write("                      <TD >&nbsp;&nbsp;");
 if("selectGuidemap".equals(url)){
      out.write("<A href=\"javascript:selectGuidemap();\" >");
 }else{
      out.write("<A href=");
      out.print(url);
      out.write(" target=\"view\">");
} 
      out.write("\r\n");
      out.write("                        <!--IMG height=\"13\" src=\"../images/menu_index08.gif\" width=\"50\" border=\"0\"-->\r\n");
      out.write("                       ");
      out.print(message.getMessage("LBL_DAOHANGTU"));
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("                      ");
} 
      out.write("\r\n");
      out.write("                      <!-- \r\n");
      out.write("                      <TD width=\"34\"><IMG height=\"13\" src=\"../images/dot_index02.gif\" width=\"34\"></TD>\r\n");
      out.write("                      <TD width=\"52\"><A href=\"#\">\r\n");
      out.write("                        <!--IMG height=\"13\" src=\"../images/menu_index09.gif\" width=\"52\" border=\"0\">");
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("                       -->\r\n");
      out.write("                       \r\n");
      out.write("                      <TD >");
      out.write("</TD>\r\n");
      out.write("                      <TD  id=\"tags\">\r\n");
      out.write("                        &nbsp;&nbsp;<A href=\"javascript:showFunList();\">");
      out.print(message.getMessage("LBL_SYSMANAGER"));
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                      ");
      out.write("\r\n");
      out.write("                      <TD >\r\n");
      out.write("                        &nbsp;&nbsp;<A href=\"../main/login.jsp\" target=\"_parent\">");
      out.print(message.getMessage("BTN_EXISYS"));
      out.write("</A>\r\n");
      out.write("                      </TD>\r\n");
      out.write("             \r\n");
      out.write("                      </TR></TBODY></TABLE>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          <TD align=\"right\">\r\n");
      out.write("            <TABLE cellSpacing=\"0\" cellPadding=\"0\" width=\"5\" border=\"0\" bgcolor=\"#EFEFDF\">\r\n");
      out.write("              <TBODY>\r\n");
      out.write("              <TR>\r\n");
      out.write("                <TD> <IMG  height=\"36\" src=\"../images/topmenu1/menu_bg.gif\" width=\"10\"></TD>\r\n");
      out.write("              </TR>\r\n");
      out.write("              </TBODY>\r\n");
      out.write("              </TABLE>\r\n");
      out.write("         </TD>\r\n");
      out.write("         \r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY></TABLE>\r\n");
      out.write("\r\n");
      out.write("        <TABLE cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" height=\"25\" background=\"../images/xtpic_16red.gif\" border=\"0\">\r\n");
      out.write("   <TBODY>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write(" </TBODY></TABLE>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
